In [1]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv(r'C:\Users\indur\OneDrive\Desktop\power bi projects\Public_Transport_Delay\public_transport_delay_cleaned.csv')

In [18]:
df['WIND_SPEED'] = df['WIND_SPEED'].str.replace(r'[^0-9.]','',regex=True)
df['WIND_SPEED'] = df['WIND_SPEED'].astype(float)

In [19]:
df['EVENT_TYPE'] = df['EVENT_TYPE'].fillna('IPL_Match')
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Metro,16min
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19min
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7min
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Train,17min
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,Yes,Medium_Traffic,No,IPL_Match,YES,Bus,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,No,High_Traffic,Yes,Concert,NO,Bus,19min
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,Yes,High_Traffic,Yes,Concert,YES,Metro,22min
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,Yes,High_Traffic,Yes,Concert,NO,Bus,33min
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16min
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14min

In [20]:
df['DELAY_MINUTES'] = df['DELAY_MINUTES'].replace(r'[^0-9]','',regex=True)
df['DELAY_MINUTES'] = df['DELAY_MINUTES'].astype(int)
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Metro,16
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Train,17
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,Yes,Medium_Traffic,No,IPL_Match,YES,Bus,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,No,High_Traffic,Yes,Concert,NO,Bus,19
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,Yes,High_Traffic,Yes,Concert,YES,Metro,22
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,Yes,High_Traffic,Yes,Concert,NO,Bus,33
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14

In [21]:
# aggregation feature engineering

df['AVG_DELAY_PER_CITY']  = df.groupby('CITY')['DELAY_MINUTES'].transform('mean')
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Metro,16,40.067270
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19,41.018889
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7,38.832169
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Train,17,40.067270
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,Yes,Medium_Traffic,No,IPL_Match,YES,Bus,13,38.832169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,No,High_Traffic,Yes,Concert,NO,Bus,19,41.018889
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,Yes,High_Traffic,Yes,Concert,YES,Metro,22,38.832169
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,Yes,High_Traffic,Yes,Concert,NO,Bus,33,41.075690
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16,41.018889
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14,40.082482

In [22]:
# aggregation feature engineering

df['AVG_DELAY_PER_CITY']  = df.groupby('CITY')['DELAY_MINUTES'].transform('mean')
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Metro,16,40.067270
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19,41.018889
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7,38.832169
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,Yes,Low_Traffic,Yes,IPL_Match,NO,Train,17,40.067270
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,Yes,Medium_Traffic,No,IPL_Match,YES,Bus,13,38.832169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,No,High_Traffic,Yes,Concert,NO,Bus,19,41.018889
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,Yes,High_Traffic,Yes,Concert,YES,Metro,22,38.832169
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,Yes,High_Traffic,Yes,Concert,NO,Bus,33,41.075690
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16,41.018889
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14,40.082482

In [23]:
df["RUSH_HOUR"] = df["RUSH_HOUR"].map({"Yes":1,"No":0,"True":1,"False":0})
df["EVENT_TODAY"] = df["EVENT_TODAY"].map({"Yes":1,"No":0})
df["IS_WEEKEND"] = df["IS_WEEKEND"].map({"YES":1,"NO":0})
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,1,Low_Traffic,1,IPL_Match,0,Metro,16,40.067270
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,0,Medium_Traffic,1,IPL_Match,1,Bus,19,41.018889
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,1,Low_Traffic,1,Cricket_Match,0,Bus,7,38.832169
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,1,Low_Traffic,1,IPL_Match,0,Train,17,40.067270
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,1,Medium_Traffic,0,IPL_Match,1,Bus,13,38.832169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,0,High_Traffic,1,Concert,0,Bus,19,41.018889
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,1,High_Traffic,1,Concert,1,Metro,22,38.832169
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,1,High_Traffic,1,Concert,0,Bus,33,41.075690
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,1,Medium_Traffic,1,IPL_Match,0,Train,16,41.018889
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,1,Medium_Traffic,1,IPL_Match,1,Bus,14,40.082482

In [25]:
df["TRAFFIC_LEVEL"] = df["TRAFFIC_LEVEL"].str.replace(r"[^A-Za-z_]", "", regex=True)
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY
0,0,TR1,Hyderabad,Busss88,4,Saturday,9.9,28.0,79.0,15.0,1,Low_Traffic,1,IPL_Match,0,Metro,16,40.067270
1,1,TR2,Delhi,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,0,Medium_Traffic,1,IPL_Match,1,Bus,19,41.018889
2,2,TR3,Chennai,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,1,Low_Traffic,1,Cricket_Match,0,Bus,7,38.832169
3,3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28.0,66.0,15.0,1,Low_Traffic,1,IPL_Match,0,Train,17,40.067270
4,4,TR5,Chennai,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,1,Medium_Traffic,0,IPL_Match,1,Bus,13,38.832169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32.0,88.8,99.0,0,High_Traffic,1,Concert,0,Bus,19,41.018889
44996,44996,TR44997,Chennai,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,1,High_Traffic,1,Concert,1,Metro,22,38.832169
44997,44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,1,High_Traffic,1,Concert,0,Bus,33,41.075690
44998,44998,TR44999,Delhi,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,1,Medium_Traffic,1,IPL_Match,0,Train,16,41.018889
44999,44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85.0,14.0,1,Medium_Traffic,1,IPL_Match,1,Bus,14,40.082482

In [26]:
df['CITY'] = df['CITY'].map({'Hyderabad':1,'Bangalore':2,'Chennai':3,'Mumbai':4,'Delhi':5})
df['CITY'] = df['CITY'].fillna(df['CITY'].median())
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY
0,0,TR1,1,Busss88,4,Saturday,9.9,28.0,79.0,15.0,1,Low_Traffic,1,IPL_Match,0,Metro,16,40.067270
1,1,TR2,5,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,0,Medium_Traffic,1,IPL_Match,1,Bus,19,41.018889
2,2,TR3,3,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,1,Low_Traffic,1,Cricket_Match,0,Bus,7,38.832169
3,3,TR4,1,Local_Train,3,Friday,5.7,28.0,66.0,15.0,1,Low_Traffic,1,IPL_Match,0,Train,17,40.067270
4,4,TR5,3,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,1,Medium_Traffic,0,IPL_Match,1,Bus,13,38.832169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,5,Metrored,14,Sunday,7.2,32.0,88.8,99.0,0,High_Traffic,1,Concert,0,Bus,19,41.018889
44996,44996,TR44997,3,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,1,High_Traffic,1,Concert,1,Metro,22,38.832169
44997,44997,TR44998,4,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,1,High_Traffic,1,Concert,0,Bus,33,41.075690
44998,44998,TR44999,5,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,1,Medium_Traffic,1,IPL_Match,0,Train,16,41.018889
44999,44999,TR45000,2,Metrored,21,Saturday,8.1,31.1,85.0,14.0,1,Medium_Traffic,1,IPL_Match,1,Bus,14,40.082482

In [27]:
df['AVG_DELAY_PER_TRAFFIC_LEVEL'] = df.groupby('TRAFFIC_LEVEL')['DELAY_MINUTES'].transform('mean')
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY,AVG_DELAY_PER_TRAFFIC_LEVEL
0,0,TR1,1,Busss88,4,Saturday,9.9,28.0,79.0,15.0,1,Low_Traffic,1,IPL_Match,0,Metro,16,40.067270,39.623918
1,1,TR2,5,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,0,Medium_Traffic,1,IPL_Match,1,Bus,19,41.018889,41.208468
2,2,TR3,3,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,1,Low_Traffic,1,Cricket_Match,0,Bus,7,38.832169,39.623918
3,3,TR4,1,Local_Train,3,Friday,5.7,28.0,66.0,15.0,1,Low_Traffic,1,IPL_Match,0,Train,17,40.067270,39.623918
4,4,TR5,3,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,1,Medium_Traffic,0,IPL_Match,1,Bus,13,38.832169,41.208468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,5,Metrored,14,Sunday,7.2,32.0,88.8,99.0,0,High_Traffic,1,Concert,0,Bus,19,41.018889,40.843435
44996,44996,TR44997,3,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,1,High_Traffic,1,Concert,1,Metro,22,38.832169,40.843435
44997,44997,TR44998,4,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,1,High_Traffic,1,Concert,0,Bus,33,41.075690,40.843435
44998,44998,TR44999,5,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,1,Medium_Traffic,1,IPL_Match,0,Train,16,41.018889,41.208468
44999,44999,TR45000,2,Metrored,21,Saturday,8.1,31.1,85.0,14.0,1,Medium_Traffic,1,IPL_Match,1,Bus,14,40.082482,41.208468

In [28]:
df['TRAFFIC_LEVEL'] = df['TRAFFIC_LEVEL'].map({'Low_Traffic':1,'Medium_Traffic':2,'High_Traffic':3})
df['TRAFFIC_LEVEL'] =df['TRAFFIC_LEVEL'].fillna(df['TRAFFIC_LEVEL'].median())
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY,AVG_DELAY_PER_TRAFFIC_LEVEL
0,0,TR1,1,Busss88,4,Saturday,9.9,28.0,79.0,15.0,1,1.0,1,IPL_Match,0,Metro,16,40.067270,39.623918
1,1,TR2,5,Busss55,20,Saturday,6.7.7,34.0,52.0,9.0,0,2.0,1,IPL_Match,1,Bus,19,41.018889,41.208468
2,2,TR3,3,Local_Train,10,Saturday,1.3,25.0,93.0,13.0,1,1.0,1,Cricket_Match,0,Bus,7,38.832169,39.623918
3,3,TR4,1,Local_Train,3,Friday,5.7,28.0,66.0,15.0,1,1.0,1,IPL_Match,0,Train,17,40.067270,39.623918
4,4,TR5,3,Busss55,3,Sunday,6.9.9,35.5,56.0,11.0,1,2.0,0,IPL_Match,1,Bus,13,38.832169,41.208468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,5,Metrored,14,Sunday,7.2,32.0,88.8,99.0,0,3.0,1,Concert,0,Bus,19,41.018889,40.843435
44996,44996,TR44997,3,Busss88,2,Monday,8.7.7,34.4,78.8,8.0,1,3.0,1,Concert,1,Metro,22,38.832169,40.843435
44997,44997,TR44998,4,Metrored,12,Wednesday,2.1.1,27.0,84.0,8.0,1,3.0,1,Concert,0,Bus,33,41.075690,40.843435
44998,44998,TR44999,5,Busss88,15,Saturday,4.9.9,27.0,52.0,88.0,1,2.0,1,IPL_Match,0,Train,16,41.018889,41.208468
44999,44999,TR45000,2,Metrored,21,Saturday,8.1,31.1,85.0,14.0,1,2.0,1,IPL_Match,1,Bus,14,40.082482,41.208468

In [29]:
df['ROUTE_ID'] = df['ROUTE_ID'].map({'Busss88':1,'Busss55':2,'Local_Train':3,'Metrored':4,'Metrored':5})
df['ROUTE_ID'] = df['ROUTE_ID'].fillna(df['ROUTE_ID'].median())
df




df['EVENT_TYPE'] = df['EVENT_TYPE'].map({'IPL_Match':1,'Cricket_Match':2,'Concert':3})
df['EVENT_TYPE'] = df['EVENT_TYPE'].fillna(df['EVENT_TYPE'].median())
df

df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].map({'Metro':1,'Bus':2,'Train':3})
df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].fillna(df['VEHICLE_TYPE'].median())
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY,AVG_DELAY_PER_TRAFFIC_LEVEL
0,0,TR1,1,1.0,4,Saturday,9.9,28.0,79.0,15.0,1,1.0,1,1.0,0,1,16,40.067270,39.623918
1,1,TR2,5,2.0,20,Saturday,6.7.7,34.0,52.0,9.0,0,2.0,1,1.0,1,2,19,41.018889,41.208468
2,2,TR3,3,3.0,10,Saturday,1.3,25.0,93.0,13.0,1,1.0,1,2.0,0,2,7,38.832169,39.623918
3,3,TR4,1,3.0,3,Friday,5.7,28.0,66.0,15.0,1,1.0,1,1.0,0,3,17,40.067270,39.623918
4,4,TR5,3,2.0,3,Sunday,6.9.9,35.5,56.0,11.0,1,2.0,0,1.0,1,2,13,38.832169,41.208468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,5,5.0,14,Sunday,7.2,32.0,88.8,99.0,0,3.0,1,3.0,0,2,19,41.018889,40.843435
44996,44996,TR44997,3,1.0,2,Monday,8.7.7,34.4,78.8,8.0,1,3.0,1,3.0,1,1,22,38.832169,40.843435
44997,44997,TR44998,4,5.0,12,Wednesday,2.1.1,27.0,84.0,8.0,1,3.0,1,3.0,0,2,33,41.075690,40.843435
44998,44998,TR44999,5,1.0,15,Saturday,4.9.9,27.0,52.0,88.0,1,2.0,1,1.0,0,3,16,41.018889,41.208468
44999,44999,TR45000,2,5.0,21,Saturday,8.1,31.1,85.0,14.0,1,2.0,1,1.0,1,2,14,40.082482,41.208468

In [31]:
# feature engineering 

df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].map({'Monday':1,'Tuesday':2,'Wednesday':3,'Thursday':4,'Friday':5,'Saturday':6,'Sunday':7})
df

,Unnamed: 0,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES,AVG_DELAY_PER_CITY,AVG_DELAY_PER_TRAFFIC_LEVEL,HUMIDITY_TEMP_RATIO
0,0,TR1,1,1.0,4,6,9.9,28.0,79.0,15.0,1,1.0,1,1.0,0,1,16,40.067270,39.623918,2.821429
1,1,TR2,5,2.0,20,6,6.7.7,34.0,52.0,9.0,0,2.0,1,1.0,1,2,19,41.018889,41.208468,1.529412
2,2,TR3,3,3.0,10,6,1.3,25.0,93.0,13.0,1,1.0,1,2.0,0,2,7,38.832169,39.623918,3.720000
3,3,TR4,1,3.0,3,5,5.7,28.0,66.0,15.0,1,1.0,1,1.0,0,3,17,40.067270,39.623918,2.357143
4,4,TR5,3,2.0,3,7,6.9.9,35.5,56.0,11.0,1,2.0,0,1.0,1,2,13,38.832169,41.208468,1.577465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,44995,TR44996,5,5.0,14,7,7.2,32.0,88.8,99.0,0,3.0,1,3.0,0,2,19,41.018889,40.843435,2.775000
44996,44996,TR44997,3,1.0,2,1,8.7.7,34.4,78.8,8.0,1,3.0,1,3.0,1,1,22,38.832169,40.843435,2.290698
44997,44997,TR44998,4,5.0,12,3,2.1.1,27.0,84.0,8.0,1,3.0,1,3.0,0,2,33,41.075690,40.843435,3.111111
44998,44998,TR44999,5,1.0,15,6,4.9.9,27.0,52.0,88.0,1,2.0,1,1.0,0,3,16,41.018889,41.208468,1.925926
44999,44999,TR45000,2,5.0,21,6,8.1,31.1,85.0,14.0,1,2.0,1,1.0,1,2,14,40.082482,41.208468,2.733119

In [32]:

df['HUMIDITY_TEMP_RATIO'] = df['HUMIDITY'] / df['TEMPERATURE']

In [33]:
df.to_csv('cleaned_data.csv',index=False)