In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\indur\OneDrive\Desktop\power bi projects\Public_Transport_Delay\ETL\public_transport_delay_messy_45000.csv')
df

,trip_id,city,route_id,hour,day_of_week,rainfall_mm,temperature,humidity,wind_speed,rush_hour,traffic_level,event_today,event_type,is_weekend,vehicle_type,delay_minutes
0,TR!8EKVIK,Hyd!der@bad99,Bu$88@@,04am!!,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR!9LGUKW,D3lhi!@,Bu$-55##,20am!!,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR!DSHK96,Chenn@i99,L0cal_Tr@in##,10hr!!,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR!ITLZ02,Hyd!der@bad99,L0cal_Tr@in##,3:30pm,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR!9S35KP,Chenn@i99,Bu$-55##,03am!!,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR!LR2UTD,D3lhi!@,Metr0#Red!!,14:30pm,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR!C07T1C,Chenn@i99,Bu$88@@,2:30pm,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR!1QK1VI,Mumb@i!!,Metr0#Red!!,12:30pm,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR!JU11#O,D3lhi!@,Bu$88@@,15:30pm,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR!SC4GS8,B@ng@l0re!!,Metr0#Red!!,21:00pm,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [3]:
df.columns = df.columns.str.upper()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR!8EKVIK,Hyd!der@bad99,Bu$88@@,04am!!,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR!9LGUKW,D3lhi!@,Bu$-55##,20am!!,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR!DSHK96,Chenn@i99,L0cal_Tr@in##,10hr!!,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR!ITLZ02,Hyd!der@bad99,L0cal_Tr@in##,3:30pm,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR!9S35KP,Chenn@i99,Bu$-55##,03am!!,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR!LR2UTD,D3lhi!@,Metr0#Red!!,14:30pm,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR!C07T1C,Chenn@i99,Bu$88@@,2:30pm,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR!1QK1VI,Mumb@i!!,Metr0#Red!!,12:30pm,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR!JU11#O,D3lhi!@,Bu$88@@,15:30pm,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR!SC4GS8,B@ng@l0re!!,Metr0#Red!!,21:00pm,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [4]:
#about data before the data cleaning 
print(df.describe())
print(df.info())
print(df.isna().sum())
print(df.shape)
print(df.sample(10))
print(df.head())
print(df.tail())
df.duplicated().sum()
print(df.dtypes)

          TRIP_ID         CITY       ROUTE_ID     HOUR DAY_OF_WEEK  \
count       45000        45000          45000    45000       45000
unique      45000            5              5       96           5
top     TR!SC4GS8  B@ng@l0re!!  L0cal_Tr@in##  16:00pm       Mon@@
freq            1         9105           9136      534        9186

       RAINFALL_MM TEMPERATURE HUMIDITY WIND_SPEED RUSH_HOUR TRAFFIC_LEVEL  \
count        45000       45000    45000      45000     45000         45000
unique         404          48      184         44         5             5
top        2.5mm##         26C    79%##   8..8km/h     yes!!   L0w_Tr@ffic
freq           146         995      279       1100      9099          9123

       EVENT_TODAY  EVENT_TYPE IS_WEEKEND VEHICLE_TYPE DELAY_MINUTES
count        45000       45000      45000        45000         45000
unique           3           5          4            5           104
top            N!!  Fest!val@@        1!!      Metr0!!      10..0min
freq         15004        9105      11365         9113           808
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TRIP_ID        45000 non-null  object
 1   CITY           45000 non-null  object
 2   ROUTE_ID       45000 non-null  object
 3   HOUR           45000 non-null  object
 4   DAY_OF_WEEK    45000 non-null  object
 5   RAINFALL_MM    45000 non-null  object
 6   TEMPERATURE    45000 non-null  object
 7   HUMIDITY       45000 non-null  object
 8   WIND_SPEED     45000 non-null  object
 9   RUSH_HOUR      45000 non-null  object
 10  TRAFFIC_LEVEL  45000 non-null  object
 11  EVENT_TODAY    45000 non-null  object
 12  EVENT_TYPE     45000 non-null  object
 13  IS_WEEKEND     45000 non-null  object
 14  VEHICLE_TYPE   45000 non-null  object
 15  DELAY_MINUTES  45000 non-null  object
dtypes: object(16)
memory usage: 5.5+ MB
None
TRIP_ID          0
CITY             0
ROUTE_ID         0
HOUR             0
DAY_OF_WEEK      0
RAINFALL_MM      0
TEMPERATURE      0
HUMIDITY         0
WIND_SPEED       0
RUSH_HOUR        0
TRAFFIC_LEVEL    0
EVENT_TODAY      0
EVENT_TYPE       0
IS_WEEKEND       0
VEHICLE_TYPE     0
DELAY_MINUTES    0
dtype: int64
(45000, 16)
         TRIP_ID           CITY     ROUTE_ID     HOUR DAY_OF_WEEK RAINFALL_MM  \
15257  TR!6Q#74W        D3lhi!@      Bu$88@@  18:30pm       W3d@@     5.8mm##
1056   TR!R0MFAM        D3lhi!@     Bu$-55##  21:30pm       W3d@@     5.7mm!!
35074  TR!6E6@QX    B@ng@l0re!!     Bu$-45@A  18:00pm     Fr!day@     4.7mm##
27923  TR!PGNZGA      Chenn@i99     Bu$-55##   12hr!!       Mon@@     5.4mm##
5662   TR!4EKGMC    B@ng@l0re!!     Bu$-45@A   2:30pm       W3d@@     9.5mm##
2608   TR!1Q3OR8        D3lhi!@      Bu$88@@   14am!!       Sun!!       5.2mm
40446  TR!USSAR7      Chenn@i99  Metr0#Red!!   3:00pm   Sat!urday     7.2mm!!
26319  TR!5N4Q48      Chenn@i99      Bu$88@@   2:00pm       W3d@@     8.6mm##
23241  TR!HU9GWF  Hyd!der@bad99      Bu$88@@   10am!!     Fr!day@       5.4mm
38823  TR!85PRLT       Mumb@i!!      Bu$88@@   10hr!!     Fr!day@    8.1..1mm

      TEMPERATURE HUMIDITY WIND_SPEED RUSH_HOUR   TRAFFIC_LEVEL EVENT_TODAY  \
15257         25C      81%      8km/h     YES!!     H!GH_traf!!         N!!
1056        27C!!      77%   15km/h##       1@@    H!gh_Traff!c       YES!!
35074       26C!!   72..2%   9..9km/h       0!!    H!gh_Traff!c         N!!
27923         29C      83%  13..3km/h     YES!!  Med!um_tr@ffic         N!!
5662          30C      54%   11km/h##     yes!!     H!GH_traf!!       YES!!
2608          25C    55%!!    8km/h##    TRUE##         H!gh###         N!!
40446       32C!!    93%##  15..5km/h     YES!!         H!gh###       YES!!
26319         31C    88%##   10km/h!!       1@@         H!gh###         N!!
23241      34..4C      89%    8km/h##     yes!!     L0w_Tr@ffic       YES!!
38823       30C##      86%    5km/h!!       0!!         H!gh###       YES!!

            EVENT_TYPE IS_WEEKEND VEHICLE_TYPE DELAY_MINUTES
15257           N0ne!!        0##      Metr0!!         10min
1056   Crick3t_M@tch!!      F@lse        Tr@in       13min##
35074     IPL_M@tch###       TRUE          bu$         13min
27923     IPL_M@tch###       TRUE        Tr@in      12..2min
5662         Conc3rt@@      F@lse        Tr@in       21min!!
2608      IPL_M@tch###        1!!         BUs@       9..9min
40446  Crick3t_M@tch!!       TRUE        Tr@in       14min##
26319     IPL_M@tch###      F@lse      Metr0!!         15min
23241       Fest!val@@      F@lse         BUs@      16..6min
38823       Fest!val@@        1!!        Bu$##       16min##
     TRIP_ID           CITY       ROUTE_ID    HOUR DAY_OF_WEEK RAINFALL_MM  \
0  TR!8EKVIK  Hyd!der@bad99        Bu$88@@  04am!!   Sat!urday       9.9mm
1  TR!9LGUKW        D3lhi!@       Bu$-55##  20am!!   Sat!urday    6.7..7mm
2  TR!DSHK96      Chenn@i99  L0cal_Tr@in##  10hr!!   Sat!urday       1.3mm
3  TR!ITLZ02  Hyd!der@bad99  L0cal_Tr@in##  3:30pm     Fr!day@       5.7mm
4  TR!9S35KP      Chenn@i99       Bu$-55##  03am!!       Sun!!    6.9..9mm

  TEMPERATURE HUMIDITY WIND_SPEED RUSH_HOUR   TRAFFIC_LEVEL EVENT_TODAY  \
0         28C    79%!!     15km/h     yes!!     L0w_Tr@ffic       YES!!
1         34C      52%    9km/h!!       0!!  Med!um_tr@ffic       YES!!
2       25C!!      93%   13km/h##     yes!!     L0w_Tr@ffic          Y@
3       28C##    66%##   15km/h##       1@@     L0w_Tr@ffic       YES!!
4      35..5C    56%!!   11km/h##     YES!!  Med!um_tr@ffic         N!!

        EVENT_TYPE IS_WEEKEND VEHICLE_TYPE DELAY_MINUTES
0           N0ne!!      F@lse      Metr0!!       16min##
1     IPL_M@tch###        1!!         BUs@         19min
2  Crick3t_M@tch!!        0##         BUs@        7min##
3           N0ne!!      F@lse        Tr@in         17min
4           N0ne!!       TRUE        Bu$##         13min
         TRIP_ID         CITY     ROUTE_ID     HOUR DAY_OF_WEEK RAINFALL_MM  \
44995  TR!LR2UTD      D3lhi!@  Metr0#Red!!  14:30pm       Sun!!       7.2mm
44996  TR!C07T1C    Chenn@i99      Bu$88@@   2:30pm       Mon@@    8.7..7mm
44997  TR!1QK1VI     Mumb@i!!  Metr0#Red!!  12:30pm       W3d@@    2.1..1mm
44998  TR!JU11#O      D3lhi!@      Bu$88@@  15:30pm   Sat!urday    4.9..9mm
44999  TR!SC4GS8  B@ng@l0re!!  Metr0#Red!!  21:00pm   Sat!urday     8.1mm##

      TEMPERATURE HUMIDITY WIND_SPEED RUSH_HOUR   TRAFFIC_LEVEL EVENT_TODAY  \
44995         32C   88..8%   9..9km/h       0!!    H!gh_Traff!c       YES!!
44996      34..4C   78..8%    8km/h##       1@@    H!gh_Traff!c       YES!!
44997         27C      84%    8km/h!!       1@@    H!gh_Traff!c          Y@
44998         27C    52%##   8..8km/h       1@@  Med!um_tr@ffic          Y@
44999      31..1C    85%!!   14km/h##    TRUE##  Med!um_tr@ffic       YES!!

         EVENT_TYPE IS_WEEKEND VEHICLE_TYPE DELAY_MINUTES
44995     Conc3rt@@      F@lse        Bu$##       19min!!
44996     Conc3rt@@       TRUE      Metr0!!       22min##
44997     Conc3rt@@        0##          bu$       3..3min
44998  IPL_M@tch###        0##        Tr@in         16min
44999  IPL_M@tch###        1!!          bu$       14min##
TRIP_ID          object
CITY             object
ROUTE_ID         object
HOUR             object
DAY_OF_WEEK      object
RAINFALL_MM      object
TEMPERATURE      object
HUMIDITY         object
WIND_SPEED       object
RUSH_HOUR        object
TRAFFIC_LEVEL    object
EVENT_TODAY      object
EVENT_TYPE       object
IS_WEEKEND       object
VEHICLE_TYPE     object
DELAY_MINUTES    object
dtype: object

In [5]:
print('---------------------------------------------CLEANING--------------------------------------------------')

---------------------------------------------CLEANING--------------------------------------------------

In [6]:
# trip_id column

df['TRIP_ID'] = range(1,len(df)+1)
df['TRIP_ID'] = 'TR' + df['TRIP_ID'].astype(str)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyd!der@bad99,Bu$88@@,04am!!,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,D3lhi!@,Bu$-55##,20am!!,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chenn@i99,L0cal_Tr@in##,10hr!!,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyd!der@bad99,L0cal_Tr@in##,3:30pm,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chenn@i99,Bu$-55##,03am!!,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,D3lhi!@,Metr0#Red!!,14:30pm,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chenn@i99,Bu$88@@,2:30pm,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumb@i!!,Metr0#Red!!,12:30pm,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,D3lhi!@,Bu$88@@,15:30pm,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,B@ng@l0re!!,Metr0#Red!!,21:00pm,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [7]:
#cleaning city column

df['CITY'] = df['CITY'].str.replace(r'[^A-Za-z]','',regex=True)
df['CITY'] =df['CITY'].replace({'Hydderbad':'Hyderabad','Dlhi':'Delhi','Chenni':'Chennai','Mumbi':'Mumbai','Bnglre':'Bangalore'},regex=False).astype('category')
df['CITY'] = df['CITY'].str.strip().str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bu$88@@,04am!!,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bu$-55##,20am!!,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,L0cal_Tr@in##,10hr!!,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,L0cal_Tr@in##,3:30pm,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bu$-55##,03am!!,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metr0#Red!!,14:30pm,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bu$88@@,2:30pm,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metr0#Red!!,12:30pm,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bu$88@@,15:30pm,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metr0#Red!!,21:00pm,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [8]:

#cleaning route_id

df['ROUTE_ID'] =df['ROUTE_ID'].str.replace(r'[^A-Za-z0-9_]','',regex=True)
df['ROUTE_ID'] = df['ROUTE_ID'].str.replace('Bu','bus')
df['ROUTE_ID'] = df['ROUTE_ID'].str.replace('0','o')
df['ROUTE_ID'] = df['ROUTE_ID'].str.replace('Trin','Train')
df['ROUTE_ID'] = df['ROUTE_ID'].str.strip().str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04am!!,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20am!!,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10hr!!,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3:30pm,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03am!!,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14:30pm,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2:30pm,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12:30pm,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15:30pm,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21:00pm,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [9]:
#cleaning hour column 

df['HOUR'] =df['HOUR'].str.extract(r'(\d+)')
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Sat!urday,9.9mm,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Sat!urday,6.7..7mm,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Sat!urday,1.3mm,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Fr!day@,5.7mm,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sun!!,6.9..9mm,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sun!!,7.2mm,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Mon@@,8.7..7mm,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,W3d@@,2.1..1mm,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Sat!urday,4.9..9mm,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Sat!urday,8.1mm##,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [10]:
df['RAINFALL_MM'] = df['RAINFALL_MM'].astype(str)
df['RAINFALL_MM'] = df['RAINFALL_MM'].str.replace(r'[^0-9.]','',regex=True)
df['RAINFALL_MM'] = df['RAINFALL_MM'].str.replace(r'\.+','.',regex=True)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Sat!urday,9.9,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Sat!urday,6.7.7,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Sat!urday,1.3,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Fr!day@,5.7,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sun!!,6.9.9,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sun!!,7.2,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Mon@@,8.7.7,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,W3d@@,2.1.1,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Sat!urday,4.9.9,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Sat!urday,8.1,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [11]:
#cleaning day_of_week

df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].str.replace(r'[^A-Za-z]','',regex=True)
df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].replace({'Saturday':'saturday','Frday':'friday','Sun':'sunday','Mon':'monday','Wd':'wednesday'})
df['DAY_OF_WEEK'] = df['DAY_OF_WEEK'].str.strip().str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28C,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34C,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25C!!,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28C##,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35..5C,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32C,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34..4C,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27C,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27C,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31..1C,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [12]:
#cleaning temperature column

df['TEMPERATURE'] = df['TEMPERATURE'].str.replace(r'[^0-9.]','',regex=True)
df['TEMPERATURE'] = df['TEMPERATURE'].str.replace(r'\.+','.',regex=True)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79%!!,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52%,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93%,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66%##,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56%!!,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88..8%,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78..8%,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84%,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52%##,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85%!!,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [13]:
#cleaning humidity

df['HUMIDITY'] = df['HUMIDITY'].str.replace(r'[^0-9.]','',regex=True)
df['HUMIDITY'] = df['HUMIDITY'].str.replace(r'\.+','.',regex=True)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h!!,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h##,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h##,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h##,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,9..9km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h##,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h!!,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,8..8km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h##,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [14]:
#cleaning wind_speed

df['WIND_SPEED'] = df['WIND_SPEED'].str.replace(r'[^A-Za-z0-9/]','',regex=True)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,yes!!,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,0!!,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,yes!!,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,1@@,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,YES!!,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,0!!,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,1@@,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,1@@,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,1@@,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,TRUE##,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [15]:
#CLEANING RUSH_HOUR

df['RUSH_HOUR'] = df['RUSH_HOUR'].str.replace(r'[^A-Za-z0-9]','',regex=True)
df['RUSH_HOUR'] = df['RUSH_HOUR'].replace({'0':'no','1':'yes','True':'yes','False':'no'})
df['RUSH_HOUR'] = df['RUSH_HOUR'].str.strip().str.title()

df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,L0w_Tr@ffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,L0w_Tr@ffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Med!um_tr@ffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,H!gh_Traff!c,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,H!gh_Traff!c,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,H!gh_Traff!c,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Med!um_tr@ffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Med!um_tr@ffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [16]:
#cleaning TRAFFIC_LEVEL

df['TRAFFIC_LEVEL'] = df['TRAFFIC_LEVEL'].str.replace('0','o')
df['TRAFFIC_LEVEL'] = df['TRAFFIC_LEVEL'].str.replace('@','a')
df['TRAFFIC_LEVEL'] = df['TRAFFIC_LEVEL'].str.replace('!','i')
df['TRAFFIC_LEVEL'] = df['TRAFFIC_LEVEL'].str.strip().str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,YES!!,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,YES!!,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Y@,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,YES!!,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,N!!,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,YES!!,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,YES!!,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Y@,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Y@,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,YES!!,IPL_M@tch###,1!!,bu$,14min##

In [17]:
#cleaning EVENT_TODAY

df['EVENT_TODAY'] = df['EVENT_TODAY'].str.replace(r'[^A-Za-z]','',regex=True)
df['EVENT_TODAY'] = df['EVENT_TODAY'].replace({'Y':'Yes','N':'No'}).str.strip().str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,Yes,N0ne!!,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,Yes,IPL_M@tch###,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Yes,Crick3t_M@tch!!,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,Yes,N0ne!!,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,No,N0ne!!,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,Yes,Conc3rt@@,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,Yes,Conc3rt@@,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Yes,Conc3rt@@,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Yes,IPL_M@tch###,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,Yes,IPL_M@tch###,1!!,bu$,14min##

In [18]:
#cleaning EVENT_TYPE

df['EVENT_TYPE'] = df['EVENT_TYPE'].str.replace('0','o')
df['EVENT_TYPE'] = df['EVENT_TYPE'].str.replace('@','a')
df['EVENT_TYPE'] = df['EVENT_TYPE'].str.replace('3','e')
df['EVENT_TYPE'] = df['EVENT_TYPE'].str.replace(r'[^A-Za-z_]','',regex=True)
df['EVENT_TYPE'] = df['EVENT_TYPE'].str.replace('Concertaa','Concert')
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,Yes,None,F@lse,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,Yes,IPL_Match,1!!,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Yes,Cricket_Match,0##,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,Yes,None,F@lse,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,No,None,TRUE,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,Yes,Concert,F@lse,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,Yes,Concert,TRUE,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Yes,Concert,0##,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Yes,IPL_Match,0##,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,Yes,IPL_Match,1!!,bu$,14min##

In [19]:
#cleaning IS_WEEKEND

df['IS_WEEKEND'] = df['IS_WEEKEND'].str.replace(r'[^A-Za-z0-9]','',regex=True)
df['IS_WEEKEND'] = df['IS_WEEKEND'].replace({'0':'false','1':'true','Flse':'False'}).str.strip().str.title()
df['IS_WEEKEND'] = df['IS_WEEKEND'].replace({'False':'NO','True':'YES'})
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,Yes,None,NO,Metr0!!,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,Yes,IPL_Match,YES,BUs@,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Yes,Cricket_Match,NO,BUs@,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,Yes,None,NO,Tr@in,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,No,None,YES,Bu$##,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,Yes,Concert,NO,Bu$##,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,Yes,Concert,YES,Metr0!!,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Yes,Concert,NO,bu$,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Yes,IPL_Match,NO,Tr@in,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,Yes,IPL_Match,YES,bu$,14min##

In [20]:
#cleaning VEHICLE_TYPE

df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].str.replace('0','o')
df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].str.replace('$','s')
df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].str.replace('@','a')
df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].str.replace(r'[^A-Za-z]','',regex=True)
df['VEHICLE_TYPE'] = df['VEHICLE_TYPE'].replace('BUsa','bus').str.title()
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,Yes,None,NO,Metro,16min##
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19min
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7min##
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,Yes,None,NO,Train,17min
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,No,None,YES,Bus,13min
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,Yes,Concert,NO,Bus,19min!!
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,Yes,Concert,YES,Metro,22min##
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Yes,Concert,NO,Bus,3..3min
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16min
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14min##

In [28]:
#cleaning DELAY_MINUTES

df['DELAY_MINUTES'] = df['DELAY_MINUTES'].replace(r'[^0-9]','',regex=True)
df['DELAY_MINUTES'] = df['DELAY_MINUTES'].astype(int)
df

,TRIP_ID,CITY,ROUTE_ID,HOUR,DAY_OF_WEEK,RAINFALL_MM,TEMPERATURE,HUMIDITY,WIND_SPEED,RUSH_HOUR,TRAFFIC_LEVEL,EVENT_TODAY,EVENT_TYPE,IS_WEEKEND,VEHICLE_TYPE,DELAY_MINUTES
0,TR1,Hyderabad,Bus88,04,Saturday,9.9,28,79,15km/h,Yes,Low_Traffic,Yes,None,NO,Metro,16
1,TR2,Delhi,Bus55,20,Saturday,6.7.7,34,52,9km/h,No,Medium_Traffic,Yes,IPL_Match,YES,Bus,19
2,TR3,Chennai,Local_Train,10,Saturday,1.3,25,93,13km/h,Yes,Low_Traffic,Yes,Cricket_Match,NO,Bus,7
3,TR4,Hyderabad,Local_Train,3,Friday,5.7,28,66,15km/h,Yes,Low_Traffic,Yes,None,NO,Train,17
4,TR5,Chennai,Bus55,03,Sunday,6.9.9,35.5,56,11km/h,Yes,Medium_Traffic,No,None,YES,Bus,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,TR44996,Delhi,Metrored,14,Sunday,7.2,32,88.8,99km/h,No,High_Traffic,Yes,Concert,NO,Bus,19
44996,TR44997,Chennai,Bus88,2,Monday,8.7.7,34.4,78.8,8km/h,Yes,High_Traffic,Yes,Concert,YES,Metro,22
44997,TR44998,Mumbai,Metrored,12,Wednesday,2.1.1,27,84,8km/h,Yes,High_Traffic,Yes,Concert,NO,Bus,33
44998,TR44999,Delhi,Bus88,15,Saturday,4.9.9,27,52,88km/h,Yes,Medium_Traffic,Yes,IPL_Match,NO,Train,16
44999,TR45000,Bangalore,Metrored,21,Saturday,8.1,31.1,85,14km/h,True,Medium_Traffic,Yes,IPL_Match,YES,Bus,14

In [29]:
print(df.describe())
print(df.info())
print(df.dtypes)
print(df.isnull().sum())
print(df.head())
print(df.tail())

       DELAY_MINUTES
count   45000.000000
mean       40.213444
std        55.970232
min         0.000000
25%         9.000000
50%        14.000000
75%        23.000000
max       255.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   TRIP_ID        45000 non-null  object
 1   CITY           45000 non-null  object
 2   ROUTE_ID       45000 non-null  object
 3   HOUR           45000 non-null  object
 4   DAY_OF_WEEK    45000 non-null  object
 5   RAINFALL_MM    45000 non-null  object
 6   TEMPERATURE    45000 non-null  object
 7   HUMIDITY       45000 non-null  object
 8   WIND_SPEED     45000 non-null  object
 9   RUSH_HOUR      45000 non-null  object
 10  TRAFFIC_LEVEL  45000 non-null  object
 11  EVENT_TODAY    45000 non-null  object
 12  EVENT_TYPE     45000 non-null  object
 13  IS_WEEKEND     45000 non-null  object
 14  VEHICLE_TYPE   45000 non-null  object
 15  DELAY_MINUTES  45000 non-null  int64
dtypes: int64(1), object(15)
memory usage: 5.5+ MB
None
TRIP_ID          object
CITY             object
ROUTE_ID         object
HOUR             object
DAY_OF_WEEK      object
RAINFALL_MM      object
TEMPERATURE      object
HUMIDITY         object
WIND_SPEED       object
RUSH_HOUR        object
TRAFFIC_LEVEL    object
EVENT_TODAY      object
EVENT_TYPE       object
IS_WEEKEND       object
VEHICLE_TYPE     object
DELAY_MINUTES     int64
dtype: object
TRIP_ID          0
CITY             0
ROUTE_ID         0
HOUR             0
DAY_OF_WEEK      0
RAINFALL_MM      0
TEMPERATURE      0
HUMIDITY         0
WIND_SPEED       0
RUSH_HOUR        0
TRAFFIC_LEVEL    0
EVENT_TODAY      0
EVENT_TYPE       0
IS_WEEKEND       0
VEHICLE_TYPE     0
DELAY_MINUTES    0
dtype: int64
  TRIP_ID       CITY     ROUTE_ID HOUR DAY_OF_WEEK RAINFALL_MM TEMPERATURE  \
0     TR1  Hyderabad        Bus88   04    Saturday         9.9          28
1     TR2      Delhi        Bus55   20    Saturday       6.7.7          34
2     TR3    Chennai  Local_Train   10    Saturday         1.3          25
3     TR4  Hyderabad  Local_Train    3      Friday         5.7          28
4     TR5    Chennai        Bus55   03      Sunday       6.9.9        35.5

  HUMIDITY WIND_SPEED RUSH_HOUR   TRAFFIC_LEVEL EVENT_TODAY     EVENT_TYPE  \
0       79     15km/h       Yes     Low_Traffic         Yes           None
1       52      9km/h        No  Medium_Traffic         Yes      IPL_Match
2       93     13km/h       Yes     Low_Traffic         Yes  Cricket_Match
3       66     15km/h       Yes     Low_Traffic         Yes           None
4       56     11km/h       Yes  Medium_Traffic          No           None

  IS_WEEKEND VEHICLE_TYPE  DELAY_MINUTES
0         NO        Metro             16
1        YES          Bus             19
2         NO          Bus              7
3         NO        Train             17
4        YES          Bus             13
       TRIP_ID       CITY  ROUTE_ID HOUR DAY_OF_WEEK RAINFALL_MM TEMPERATURE  \
44995  TR44996      Delhi  Metrored   14      Sunday         7.2          32
44996  TR44997    Chennai     Bus88    2      Monday       8.7.7        34.4
44997  TR44998     Mumbai  Metrored   12   Wednesday       2.1.1          27
44998  TR44999      Delhi     Bus88   15    Saturday       4.9.9          27
44999  TR45000  Bangalore  Metrored   21    Saturday         8.1        31.1

      HUMIDITY WIND_SPEED RUSH_HOUR   TRAFFIC_LEVEL EVENT_TODAY EVENT_TYPE  \
44995     88.8     99km/h        No    High_Traffic         Yes    Concert
44996     78.8      8km/h       Yes    High_Traffic         Yes    Concert
44997       84      8km/h       Yes    High_Traffic         Yes    Concert
44998       52     88km/h       Yes  Medium_Traffic         Yes  IPL_Match
44999       85     14km/h      True  Medium_Traffic         Yes  IPL_Match

      IS_WEEKEND VEHICLE_TYPE  DELAY_MINUTES
44995         NO          Bus             19
44996        YES        Metro             22
44997         NO          Bus             33
44998         NO        Train             16
44999        YES          Bus             14

In [30]:
#saving data cleaning with csv and excel files

try:
    df.to_csv('public_transport_delay_cleaned.csv')
    df.to_excel('public_transport_delay_cleaned.xlsx')
except FileExistsError:
    print('please check')
finally:
    print('successfully we saved csv and excel files..............')

successfully we saved csv and excel files..............